### ISSUE TITLE
CI script image building needs fixing

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#54]
We currently have `test.yml` and `docker-image.yml`. `test.yml` builds and tests the service and is executed on dev and main for pull requests and merges. It can also be executed by hand on any other branch.

`docker-image.yml` executes if `test.yml` succeeds and creates the production docker image and pushes it to Docker Hub.

In the event of a pull request, the `test.yml` script runs and then the `docker-image.yml` runs if the tests pass. The code from dev (before any merge) is built and made into the Docker image. This means we keep rebuilding the same code (HEAD of dev) while working on various PRs. It doesn't do any harm apart from wasting resources and being confusing.

If a manual `test.yml` job is executed on a branch, there is some evidence that the `docker-image.yml` executes on the current dev, not the branch. That's not what was intended - we want to be able to build a Docker image for any branch.

**Comment by scp93ch** [comment]
@panos tried the following script on a branch. Not clear if it worked:

```yaml
name: Docker Image CI branch

on:
  workflow_dispatch:
    inputs:
      input:
        description: "branch build"
        required: false
        default: "World"

jobs:

  build:

    runs-on: ubuntu-22.04

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: LFS checkout
      run: git lfs checkout

    - name: Build the Docker image
      # The metadata inside the image will include the final git commit SHA and the time of the final commit.
      # The tag applied to the image will be like spyderisk/system-modeller:<branch-name>-<timestamp>
      # e.g. spyderisk/system-modeller:dev-20230405T1012
      # Where the timestamp is the time of the final commit in the build.
      run: |
        TIMESTAMP=$(git show -s --format=%cI ${GITHUB_SHA})
        SHORT_TIME=$(echo ${TIMESTAMP} | sed 's/[-:]//g')
        REF_END=$(echo ${GITHUB_REF} | sed 's/.*\///')
        TAG=spyderisk/system-modeller:${REF_END}-${SHORT_TIME:0:13}
        echo "TAG=${TAG}" >> ${GITHUB_ENV}
        docker build --tag ${TAG} --build-arg CI_COMMIT_SHA=${GITHUB_SHA} --build-arg CI_COMMIT_TIMESTAMP=${TIMESTAMP} --build-arg MAVEN_USER=${{ github.actor }} --build-arg MAVEN_PASS=${{ secrets.PACKAGE_READ_SECRET }} --file Dockerfile --target ssm-production "."

    - name: Push Docker image to registry
      run: | 
        docker login -u ${{ vars.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_RW_SECRET }}
        docker push ${TAG}
```
